name: Build ClassiCube for ARMv7

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13  # macos-13 ma Xcode 14 ktory wspiera armv7!

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode 14
        run: |
          sudo xcode-select -s /Applications/Xcode_14.3.1.app
          xcodebuild -version
          xcrun --sdk iphoneos --show-sdk-version

      - name: Install dependencies
        run: brew install ldid zip

      - name: Build ARMv7 IPA
        run: |
          cd misc/ios
          make IOS_MIN_VERSION=6.0 2>&1

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ClassiCube-armv7
          path: misc/ios/ClassiCube-iPhoneOS.ipa
          retention-days: 30
