name: Build ClassiCube for ARMv7 (iOS)

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: brew install ldid zip

      - name: Build ARMv7 IPA
        run: |
          cd misc/ios
          make ARCH_32=armv7 ARCH_64=arm64 IOS_MIN_VERSION=6.0 IOS_SDK_VERSION=18.5 2>&1

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ClassiCube-armv7
          path: misc/ios/ClassiCube-iPhoneOS.ipa
          retention-days: 30
